from __future__ import annotations

import json
from collections.abc import Callable

from harness.providers.base import BaseProvider, ProviderResult


class StubProvider(BaseProvider):
    """
    Returns a structurally valid fake result without making any LLM call.

    Used for local testing via --provider stub or default_provider: stub in harness.yaml.
    Status is SUCCESS (not SKIPPED) — the agent did run, just with a stub.
    """

    def generate(
        self,
        prompt_package: dict,
        model_config: dict,
        on_token: Callable[[str], None] | None = None,
        history: list[dict] | None = None,
    ) -> ProviderResult:
        agent_name = prompt_package.get("agent_name", "unknown")
        run_id = prompt_package.get("run_id", "")
        task_id = prompt_package.get("task_id", "")

        status_block = {
            "run_id": run_id,
            "task_id": task_id,
            "agent": agent_name,
            "status": "SUCCESS",
            "summary": f"Stub run completed for {agent_name}.",
            "files_requested": [],
            "files_created": [],
            "files_modified": [],
            "files_deleted": [],
            "commands_run": [],
            "command_results": [],
            "issues_found": [],
            "human_input_required": False,
            "next_recommended_action": "Review stub output and proceed to next agent.",
            "next_agent": "",
        }

        text = (
            "## Summary\n\n"
            f"Stub run for **{agent_name}**.\n\n"
            f"- run_id: `{run_id}`\n"
            f"- task_id: `{task_id}`\n\n"
            "No real LLM call was made. This output is generated by StubProvider "
            "for local testing only.\n\n"
            "## Structured Status Block\n\n"
            "```json\n"
            + json.dumps(status_block, indent=2)
            + "\n```\n"
        )

        if on_token:
            on_token(text)

        return ProviderResult(
            text=text,
            provider="stub",
            model=model_config.get("model", "stub"),
            status="success",
            usage={
                "prompt_tokens": 1500,
                "completion_tokens": 350,
                "total_tokens": 1850,
                "cost": 0.00225,
            },
        )
